//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NinjaBuilder
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Category
    {
        public Category()
        {
            this.Equipments = new ObservableCollection<Equipment>();
        }
    
        public int Categorieid { get; set; }
        public string Naam { get; set; }
    
        public virtual ObservableCollection<Equipment> Equipments { get; set; }
    }
}
