//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NinjaBuilder
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Equipment
    {
        public int Equipmentid { get; set; }
        public int Categorieid { get; set; }
        public string Naam { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
